[pytest]
 
#Direciona o pytest a procurar os testes dentro da pasta especificada 
testpaths = tests
 
#Padrão dos arquivos de testes
python_files = test_*.py
python_classes = Test*
python_functions = test_*
 
#Configurações
addopts =
    -v
    --cov=app
    --cov-report=term-missing
    --cov-report=xml
    --cov-fail-under=70

#Categorização dos testes
markers =
    unit: testes unitários 
    integration: testes de integração